# Puerto en el que se va a ejecutar la aplicacion
server:
  port: 40003
spring:
  application:
    name: kafka
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: mygroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
